#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# scripts/android-pref-audit.sh -- the runtime pref audit (LW-M3-05).
#
# Dumps the effective values of the smoke harness's curated pref list from a
# RUNNING Android build, compares them against the checked-in baseline
# docs/android/expected-prefs.txt, and fails if -- and ONLY if -- a key
# listed in docs/android/must-lock.txt (the source of truth for privacy
# keys, generated by scripts/gen-android-locks.py) has changed.
#
# Diffs on keys that are NOT in must-lock.txt are reported as notes and do
# not fail the gate: the baseline is a curated list, not every one of its
# keys is a must-lock key, and must-not-lock keys are allowed to move.
#
# This is the regression net for the M3 privacy decisions: it catches a
# rebase or an upstream change quietly reverting a must-lock pref at
# RUNTIME, which a build that compiles and launches would not.
#
# REQUIREMENTS: a running Android environment (emulator or device with the
# APK installed) -- the smoke harness exits 2 without one, and so does this
# audit.  See docs/android/pref-audit.md, "Gap Declaration".
#
# EXIT CODES -- other scripts and CI depend on these.
#   0  every must-lock pref the harness dumps matches the baseline
#   1  at least one must-lock pref is missing from or differs from the
#      baseline -- a real regression, this is the gate going red
#   2  the audit could not run at all (missing harness, missing baseline,
#      no device/APK, malformed payload) -- never a pass, never a violation
#
# Usage:  ./scripts/android-pref-audit.sh
# ---------------------------------------------------------------------------
set -euo pipefail

usage() {
  cat <<'EOF'
android-pref-audit.sh -- audit the effective pref values of a running
LibreWolf Android build against docs/android/expected-prefs.txt.

Only diffs on keys listed in docs/android/must-lock.txt fail the gate
(exit 1); diffs on any other key are noted and do not.  Exit 2 means the
audit could not run (missing harness, missing baseline, no device) --
that is never a pass.

Regenerate the baseline on a machine with a running Android environment:
  ./scripts/generate-android-pref-baseline.sh

See docs/android/pref-audit.md for the filtering logic and the gap
declaration.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(cd "$(dirname "$SELF")/.." && pwd)"
SMOKE="$REPO_ROOT/scripts/android-smoke.sh"
BASELINE="$REPO_ROOT/docs/android/expected-prefs.txt"
MUST_LOCK="$REPO_ROOT/docs/android/must-lock.txt"
MARKER="# librewolf-android-smoke pref-dump v1"

die() {
  printf 'android-pref-audit: %s\n' "$1" >&2
  exit 2
}

# -- preflight: fail loud rather than pass silently ---------------------------
[ -f "$SMOKE" ] || die "scripts/android-smoke.sh is missing"
[ -x "$SMOKE" ] || die "scripts/android-smoke.sh is not executable"
command -v awk >/dev/null 2>&1 || die "awk is required"

[ -f "$MUST_LOCK" ] || die "docs/android/must-lock.txt is missing -- the audit has no source of truth"
must_count="$(awk '$0 !~ /^[[:space:]]*(#|$)/ { n++ } END { print n + 0 }' "$MUST_LOCK")"
[ "$must_count" -gt 0 ] || die "docs/android/must-lock.txt lists no keys -- regenerate it: python3 scripts/gen-android-locks.py"

[ -f "$BASELINE" ] || die "docs/android/expected-prefs.txt is missing -- generate it first on a machine with a running Android environment: ./scripts/generate-android-pref-baseline.sh"
first_line="$(head -n 1 "$BASELINE" 2>/dev/null || true)"
[ "$first_line" = "$MARKER" ] || die "docs/android/expected-prefs.txt does not look like a pref-dump baseline (first line: ${first_line:-<empty>})"
base_count="$(awk '$0 !~ /^[[:space:]]*(#|$)/ { n++ } END { print n + 0 }' "$BASELINE")"
[ "$base_count" -gt 0 ] || die "docs/android/expected-prefs.txt has no pref rows"

# ---------------------------------------------------------------------------
# Step (a) -- drive the settings UI.  PLACEHOLDER: the command that walks
# through every settings screen (open each, toggle nothing) is NOT part of
# this repository's local execution capabilities, so this step is a
# documented no-op for now.  When it lands, it must run AFTER the app has
# started and BEFORE the dump is taken, so that the Pref.commit() calls
# Fenix fires when its settings screens open (AGENTS.md, landmine L2, stage
# 5b) are included in the state being audited.  Until then the audit covers
# the post-startup state only, and a pref that changes only when a settings
# screen is opened will not be seen.  See docs/android/pref-audit.md,
# "Gap Declaration".
# ---------------------------------------------------------------------------
: # <ui-automation> open every settings screen (toggle nothing) -- placeholder

# ---------------------------------------------------------------------------
# Step (b) -- take the dump.
# stdout carries the payload only; stderr carries the harness's progress.
# ---------------------------------------------------------------------------
WORK="$(mktemp -d)" || die "cannot create a temporary work directory"
trap 'rm -rf "$WORK"' EXIT
DUMP="$WORK/prefs.txt"
SMOKE_ERR="$WORK/stderr.log"

rc=0
"$SMOKE" --pref-dump >"$DUMP" 2>"$SMOKE_ERR" || rc=$?
if [ "$rc" -ne 0 ]; then
  printf 'android-pref-audit: android-smoke.sh --pref-dump failed (exit %d); the audit cannot run.\n' "$rc" >&2
  if [ -s "$SMOKE_ERR" ]; then
    printf -- '--- harness stderr ---\n' >&2
    cat "$SMOKE_ERR" >&2
  else
    printf '(no stderr captured)\n' >&2
  fi
  exit 2
fi

first_line="$(head -n 1 "$DUMP" 2>/dev/null || true)"
[ "$first_line" = "$MARKER" ] || die "smoke payload does not look like a pref-dump (first line: ${first_line:-<empty>})"
dump_count="$(awk '$0 !~ /^[[:space:]]*(#|$)/ { n++ } END { print n + 0 }' "$DUMP")"
[ "$dump_count" -gt 0 ] || die "smoke payload has no pref rows"

# ---------------------------------------------------------------------------
# Steps (c)-(e) -- compare against the baseline and report.
#
# The payload is tab-separated: name<TAB>type<TAB>value<TAB>locked<TAB>user,
# so the comparison is key-based via awk, not a line diff: a reordering of
# rows (or a change in one of the two annotation columns) is only a
# violation if the key is a must-lock key and its recorded state actually
# differs.  Semantics:
#
#   must-lock key, in both files, different state   -> VIOLATION (exit 1)
#   must-lock key, in one file only                 -> VIOLATION (exit 1)
#     -- present in neither (outside the harness's curated PREF_LIST) is
#        OUT OF SCOPE for this audit: those keys are enforced by the
#        generated locks (LW-M3-04), and counting their absence here would
#        make the gate red for a healthy build.
#   any other key, anything                           -> NOTE (never fails)
# ---------------------------------------------------------------------------
awk -F '\t' '
  FNR == 1 { fileno++ }
  $0 ~ /^[[:space:]]*(#|$)/ { next }
  {
    k = $1
    sub(/[[:space:]]+$/, "", k)
    if (k == "") next
    if (fileno == 1) { if (!(k in base)) { bn++; border[bn] = k } base[k] = $0; next }
    if (fileno == 2) { if (!(k in act))  { an++; aorder[an] = k } act[k]  = $0; next }
    if (fileno == 3) { if (!(k in must)) { mn++; morder[mn] = k } must[k] = 1; next }
  }
  END {
    if (fileno < 3) {
      print "android-pref-audit: internal error: expected three input files" > "/dev/stderr"
      exit 2
    }
    viol = 0; noted = 0; inuniv = 0
    for (i = 1; i <= mn; i++) {
      k = morder[i]
      if (!(k in base) && !(k in act)) continue   # out of scope: not in the dump universe
      inuniv++
      if (!(k in base)) {
        printf("VIOLATION %s: present in the actual dump but missing from the baseline -- the baseline is stale or the build is wrong\n  actual:   %s\n", k, act[k])
        viol++
      } else if (!(k in act)) {
        printf("VIOLATION %s: in the baseline but absent from the actual dump -- the pref no longer exists in this build\n  baseline: %s\n", k, base[k])
        viol++
      } else if (base[k] != act[k]) {
        printf("VIOLATION %s: state differs from the baseline\n  baseline: %s\n  actual:   %s\n", k, base[k], act[k])
        viol++
      }
    }
    for (i = 1; i <= bn; i++) {
      k = border[i]
      if (k in must) continue
      if (!(k in act)) {
        printf("NOTE %s: in the baseline but gone from the actual dump (not a must-lock key; not a violation)\n  baseline: %s\n", k, base[k])
        noted++
      } else if (base[k] != act[k]) {
        printf("NOTE %s: differs from the baseline (not a must-lock key; not a violation)\n  baseline: %s\n  actual:   %s\n", k, base[k], act[k])
        noted++
      }
    }
    for (i = 1; i <= an; i++) {
      k = aorder[i]
      if (k in must) continue
      if (!(k in base)) {
        printf("NOTE %s: new in the actual dump, not in the baseline (not a must-lock key; not a violation)\n  actual:   %s\n", k, act[k])
        noted++
      }
    }
    printf("pref-audit: must-lock keys: %d total, %d audited, %d outside the harness dump universe (enforced by the LW-M3-04 generated locks instead)\n", mn, inuniv, mn - inuniv)
    printf("pref-audit: %d violation(s), %d non-must-lock diff(s) noted\n", viol, noted)
    if (viol > 0) exit 1
    exit 0
  }
' "$BASELINE" "$DUMP" "$MUST_LOCK"
