# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

## Redoubt Brand
##
## Redoubt is a brand name and is kept in English: not declined,
## not transliterated, not translated.
##
## Generated by scripts/gen-android-brand.py. Upstream ships Mozilla's
## Fennec branding here; these four values are what reach omni.ja and
## therefore the APK.

-brand-short-name = Redoubt
-brand-full-name = Redoubt
# Used where the product name must stay the same across channels.
-brand-product-name = Redoubt
-vendor-short-name = Redoubt
