#!/usr/bin/env python3
"""Generate Redoubt replacements for Fenix's Firefox brand imagery.

Owner: LW-M4-07 (branding). Run this to (re)generate assets/android-brand/;
scripts/librewolf-patches.py then copies those bytes over the Firefox originals
for android targets.

WHY GENERATED HERE AND CHECKED IN, rather than rendered at build time: the build
container has no image tooling and no fonts, and `scripts/android-verify-repro.sh`
requires two builds to be byte-identical. Copying checked-in bytes is trivially
reproducible and reviewable in a diff; rendering during the build would be
neither.

WHAT IT REPLACES. `--check-strings` (LW-M4-12) cleaned the string table and the
rendered settings text, and it passes. It has no view of images, and nothing else
did either, so the signed 2026-09-08 beta candidate still shipped the Firefox
flame as its home-screen wordmark and offered eight user-selectable Firefox app
icons. Measured from that APK, not inferred.

CLASSIFICATION is by shape, not by name, so an upstream rename cannot silently
skip a file:
  * wordmark TEXT  -> the word "Redoubt"
  * wide rasters   -> mark + "Redoubt" lockup, fitted
  * everything else-> the Redoubt mark (the four-bastion fort from the launcher
                      icon, so in-app art and the launcher agree)
"""
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "assets" / "android-brand"

# The launcher mark, from branding.patch. One definition, reused everywhere.
FORT = ("M46,38 L62,38 L62,27 L75,33 L81,46 L70,46 L70,62 L81,62 L75,75 "
        "L62,81 L62,70 L46,70 L46,81 L33,75 L27,62 L38,62 L38,46 L27,46 "
        "L33,33 L46,27 Z")
SLATE = "#1E293B"
WHITE = "#FFFFFF"

NAME_PATTERNS = (
    "ic_firefox", "firefox_icon", "expressive_firefox", "mozac_ic_logo_firefox_24",
    "firefox_pictorgram_shield_check_rgb_2", "ic_wordmark_logo",
    "ic_wordmark_sport_logo", "ic_wordmark_text_normal", "ic_wordmark_text_private",
    "ic_logo_wordmark_normal", "ic_logo_wordmark_private", "firefox_sport",
    "fenix_search_widget", "firefox_as_default_banner_illustration",
    "ic_launcher_foreground_cool", "ic_launcher_foreground_cuddling",
    "ic_launcher_foreground_flaming", "ic_launcher_foreground_minimal",
    "ic_launcher_foreground_momo", "ic_launcher_foreground_pixelated",
    "ic_launcher_foreground_pride", "ic_launcher_foreground_retro_2004",
)


def is_private(path: Path) -> bool:
    return "private" in path.name


def vector_for(src: Path) -> str:
    """A Redoubt mark vector that keeps the original's declared size."""
    t = src.read_text(errors="replace")

    def attr(name, default):
        m = re.search(r'android:%s="([0-9.]+)(?:dp)?"' % name, t)
        return m.group(1) if m else default

    w, h = attr("width", "24"), attr("height", "24")
    vw, vh = attr("viewportWidth", "24"), attr("viewportHeight", "24")
    # Map the 108-unit mark onto this file's viewport, centred, 80% of the box.
    scale = min(float(vw), float(vh)) / 108.0 * 0.8
    dx = (float(vw) - 108.0 * scale) / 2.0
    dy = (float(vh) - 108.0 * scale) / 2.0
    colour = WHITE if is_private(src) else SLATE
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Redoubt brand mark. Generated by scripts/gen-android-brand.py;\n"
        "     do not hand-edit. Four-bastion fort, matching the launcher icon. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="%sdp"\n    android:height="%sdp"\n'
        '    android:viewportWidth="%s"\n    android:viewportHeight="%s">\n'
        '    <group android:translateX="%.4f" android:translateY="%.4f"\n'
        '        android:scaleX="%.6f" android:scaleY="%.6f">\n'
        '        <path\n            android:fillColor="%s"\n'
        '            android:pathData="%s"/>\n'
        "    </group>\n</vector>\n"
        % (w, h, vw, vh, dx, dy, scale, scale, colour, FORT)
    )


def raster_for(src: Path, dest: Path) -> None:
    """Render a Redoubt image at the original's exact pixel size."""
    dim = subprocess.run(["identify", "-format", "%w %h", str(src)],
                         capture_output=True, text=True).stdout.split()
    if len(dim) != 2:
        raise SystemExit("cannot read dimensions of %s" % src)
    w, h = int(dim[0]), int(dim[1])
    colour = WHITE if is_private(src) else SLATE
    wide = w >= 2 * h
    text_only = src.name.startswith("ic_wordmark_text")

    svg_parts = ['<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
                 'viewBox="0 0 %d %d">' % (w, h, w, h)]
    if text_only:
        fs = h * 0.72
        svg_parts.append(
            '<text x="%g" y="%g" font-family="DejaVu Sans,Noto Sans,sans-serif" '
            'font-weight="700" font-size="%g" fill="%s" '
            'dominant-baseline="central">Redoubt</text>' % (w * 0.02, h * 0.54, fs, colour))
    elif wide:
        m = h * 0.82
        pad = h * 0.09
        s = m / 108.0
        svg_parts.append('<g transform="translate(%g,%g) scale(%g)">'
                         '<path d="%s" fill="%s"/></g>' % (pad, pad, s, FORT, colour))
        fs = h * 0.62
        svg_parts.append(
            '<text x="%g" y="%g" font-family="DejaVu Sans,Noto Sans,sans-serif" '
            'font-weight="700" font-size="%g" fill="%s" '
            'dominant-baseline="central">Redoubt</text>'
            % (pad + m + h * 0.14, h * 0.54, fs, colour))
    else:
        m = min(w, h) * 0.8
        s = m / 108.0
        svg_parts.append('<g transform="translate(%g,%g) scale(%g)">'
                         '<path d="%s" fill="%s"/></g>'
                         % ((w - m) / 2.0, (h - m) / 2.0, s, FORT, colour))
    svg_parts.append("</svg>")

    dest.parent.mkdir(parents=True, exist_ok=True)
    svg = dest.with_suffix(".svg.tmp")
    svg.write_text("\n".join(svg_parts))
    # -define webp:method=6 and a fixed quality keep the encoder deterministic.
    subprocess.run(["magick", "-background", "none", str(svg),
                    "-resize", "%dx%d!" % (w, h),
                    "-define", "webp:method=6", "-quality", "92", str(dest)],
                   check=True, capture_output=True)
    svg.unlink()


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: gen-android-brand.py <extracted-tree>", file=sys.stderr)
        return 2
    tree = Path(sys.argv[1]).resolve()
    root = tree / "mobile" / "android"
    if not root.is_dir():
        print("no mobile/android under %s" % tree, file=sys.stderr)
        return 2

    targets = []
    for p in root.rglob("*"):
        if not p.is_file() or p.suffix not in (".xml", ".webp", ".png"):
            continue
        if p.stem in NAME_PATTERNS:
            targets.append(p)
    if not targets:
        print("no brand files found — has upstream renamed them?", file=sys.stderr)
        return 1

    n_vec = n_ras = 0
    for src in sorted(targets):
        rel = src.relative_to(root)
        dest = OUT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix == ".xml":
            dest.write_text(vector_for(src))
            n_vec += 1
        else:
            raster_for(src, dest)
            n_ras += 1
    print("wrote %d vector(s) and %d raster(s) to %s"
          % (n_vec, n_ras, OUT.relative_to(REPO)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
